# Generated by Django 5.2.4 on 2025-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('confirmpass', models.CharField()),
            ],
        ),
    ]
