# Generated by Django 5.2.4 on 2025-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('pro_image', models.ImageField(upload_to='file')),
            ],
        ),
    ]
