# Generated by Django 5.2.4 on 2025-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_productinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
