# Generated by Django 5.2.4 on 2025-08-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_productinfo_pro_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='pro_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='pro_price',
            field=models.IntegerField(),
        ),
    ]
