# Generated by Django 5.2.4 on 2025-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_productinfo_pro_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pro_disc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
