# Generated by Django 5.2.4 on 2025-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_productinfo_pro_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='pro_mrp',
            field=models.IntegerField(null=True),
        ),
    ]
