# Generated by Django 5.2.4 on 2025-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('address1', models.CharField()),
                ('address2', models.CharField()),
                ('zip', models.IntegerField()),
                ('city', models.CharField()),
            ],
        ),
    ]
